// Copyright (c) 2020, 2023, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta2 "github.com/verrazzano/verrazzano/platform-operator/clientset/versioned/typed/verrazzano/v1beta2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeVerrazzanoV1beta2 struct {
	*testing.Fake
}

func (c *FakeVerrazzanoV1beta2) ModuleDefinitions(namespace string) v1beta2.ModuleDefinitionInterface {
	return &FakeModuleDefinitions{c, namespace}
}

func (c *FakeVerrazzanoV1beta2) OperatorDefinitions(namespace string) v1beta2.OperatorDefinitionInterface {
	return &FakeOperatorDefinitions{c, namespace}
}

func (c *FakeVerrazzanoV1beta2) Platforms(namespace string) v1beta2.PlatformInterface {
	return &FakePlatforms{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeVerrazzanoV1beta2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
