// Copyright (c) 2020, 2023, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta2 "github.com/verrazzano/verrazzano/platform-operator/apis/verrazzano/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVerrazzanoModules implements VerrazzanoModuleInterface
type FakeVerrazzanoModules struct {
	Fake *FakeVerrazzanoV1beta2
	ns   string
}

var verrazzanomodulesResource = schema.GroupVersionResource{Group: "verrazzano", Version: "v1beta2", Resource: "verrazzanomodules"}

var verrazzanomodulesKind = schema.GroupVersionKind{Group: "verrazzano", Version: "v1beta2", Kind: "VerrazzanoModule"}

// Get takes name of the verrazzanoModule, and returns the corresponding verrazzanoModule object, and an error if there is any.
func (c *FakeVerrazzanoModules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.VerrazzanoModule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(verrazzanomodulesResource, c.ns, name), &v1beta2.VerrazzanoModule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.VerrazzanoModule), err
}

// List takes label and field selectors, and returns the list of VerrazzanoModules that match those selectors.
func (c *FakeVerrazzanoModules) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.VerrazzanoModuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(verrazzanomodulesResource, verrazzanomodulesKind, c.ns, opts), &v1beta2.VerrazzanoModuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta2.VerrazzanoModuleList{ListMeta: obj.(*v1beta2.VerrazzanoModuleList).ListMeta}
	for _, item := range obj.(*v1beta2.VerrazzanoModuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested verrazzanoModules.
func (c *FakeVerrazzanoModules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(verrazzanomodulesResource, c.ns, opts))

}

// Create takes the representation of a verrazzanoModule and creates it.  Returns the server's representation of the verrazzanoModule, and an error, if there is any.
func (c *FakeVerrazzanoModules) Create(ctx context.Context, verrazzanoModule *v1beta2.VerrazzanoModule, opts v1.CreateOptions) (result *v1beta2.VerrazzanoModule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(verrazzanomodulesResource, c.ns, verrazzanoModule), &v1beta2.VerrazzanoModule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.VerrazzanoModule), err
}

// Update takes the representation of a verrazzanoModule and updates it. Returns the server's representation of the verrazzanoModule, and an error, if there is any.
func (c *FakeVerrazzanoModules) Update(ctx context.Context, verrazzanoModule *v1beta2.VerrazzanoModule, opts v1.UpdateOptions) (result *v1beta2.VerrazzanoModule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(verrazzanomodulesResource, c.ns, verrazzanoModule), &v1beta2.VerrazzanoModule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.VerrazzanoModule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVerrazzanoModules) UpdateStatus(ctx context.Context, verrazzanoModule *v1beta2.VerrazzanoModule, opts v1.UpdateOptions) (*v1beta2.VerrazzanoModule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(verrazzanomodulesResource, "status", c.ns, verrazzanoModule), &v1beta2.VerrazzanoModule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.VerrazzanoModule), err
}

// Delete takes name of the verrazzanoModule and deletes it. Returns an error if one occurs.
func (c *FakeVerrazzanoModules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(verrazzanomodulesResource, c.ns, name, opts), &v1beta2.VerrazzanoModule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVerrazzanoModules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(verrazzanomodulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta2.VerrazzanoModuleList{})
	return err
}

// Patch applies the patch and returns the patched verrazzanoModule.
func (c *FakeVerrazzanoModules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.VerrazzanoModule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(verrazzanomodulesResource, c.ns, name, pt, data, subresources...), &v1beta2.VerrazzanoModule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.VerrazzanoModule), err
}
