# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
FROM container-registry.oracle.com/os/oraclelinux:7-slim
COPY oracle /oracle

