{
 "title": "Thanos / Overview",
 "description": "This dashboard provides a resource usage overview of the Thanos components Querier, Query-Frontend, Compacter and Store.\r\n\r\nIt includes CPU and Memory requests, limits and usage. In addition, the last termination reason is plotted and the cache hit ratio is available.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "vzcluster",
    "label": "Verrazzano Cluster",
    "query": {
     "query": "label_values(verrazzano_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "![logo](https://repository-images.githubusercontent.com/109162639/97e49180-661b-11e9-9882-fdc44b74debd)"
   }
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count\n(\n  kube_pod_container_info{pod=~\"thanos-.*\", container!=\"istio-proxy\", verrazzano_cluster=~\"$vzcluster\"}\n) by (container)\n",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  },
  { "title": "Thanos / Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{container=\"query\", verrazzano_cluster=~\"$vzcluster\"}) by (pod) / 1000",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"query\", verrazzano_cluster=~\"$vzcluster\"}[$__interval])) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{pod=~\"thanos-query-.*\", pod!~\"thanos-query-frontend.*\", verrazzano_cluster=~\"$vzcluster\"}) by (pod)",
     "legendFormat": "{{pod}} (limit)"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"query\",verrazzano_cluster=~\"$vzcluster\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-query-[a-z0-9]*-[a-z0-9]*$\", container=\"query\", verrazzano_cluster=~\"$vzcluster\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Thanos / Query Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{container=\"query-frontend\", verrazzano_cluster=~\"$vzcluster\"}) by (pod) / 1000",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"query-frontend\", verrazzano_cluster=~\"$vzcluster\"}[$__interval])) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{pod=~\"thanos-query-frontend.*\", verrazzano_cluster=~\"$vzcluster\"}) by (pod)",
     "legendFormat": "{{pod}} (limit)"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=~\"query-frontend.*\", verrazzano_cluster=~\"$vzcluster\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-query-frontend-[a-z0-9]*-[a-z0-9]*$\", container=\"query-frontend\", verrazzano_cluster=~\"$vzcluster\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Thanos / Compact", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{container=\"compactor\", verrazzano_cluster=~\"$vzcluster\"}) by (pod) / 1000",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"compactor\", verrazzano_cluster=~\"$vzcluster\"}[$__interval])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{pod=~\"thanos-compact.*\", verrazzano_cluster=~\"$vzcluster\"}) by (pod)",
     "legendFormat": "{{pod}} (limit)"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=~\"compactor\", verrazzano_cluster=~\"$vzcluster\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-compact.*\", verrazzano_cluster=~\"$vzcluster\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Thanos / Ruler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{container=\"ruler\", verrazzano_cluster=~\"$vzcluster\"}) by (pod) / 1000",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"ruler\", verrazzano_cluster=~\"$vzcluster\"}[$__interval])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{pod=~\"thanos-ruler.*\", verrazzano_cluster=~\"$vzcluster\"}) by (pod)",
     "legendFormat": "{{pod}} (limit)"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=~\"ruler\", verrazzano_cluster=~\"$vzcluster\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-ruler.*\", container=\"ruler\", verrazzano_cluster=~\"$vzcluster\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Thanos / Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{container=\"storegateway\", verrazzano_cluster=~\"$vzcluster\"}) by (pod) / 1000",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"storegateway\", verrazzano_cluster=~\"$vzcluster\"}[$__interval])) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{pod=~\"thanos-storegateway.*\", verrazzano_cluster=~\"$vzcluster\"}) by (pod)",
     "legendFormat": "{{pod}} (limit)"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=~\"storegateway\", verrazzano_cluster=~\"$vzcluster\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-storegateway.*\", verrazzano_cluster=~\"$vzcluster\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    thanos_store_index_cache_hits_total{verrazzano_cluster=~\"$vzcluster\"}[$__rate_interval]\n  )\n)\n/\nsum(\n  rate(\n    thanos_store_index_cache_requests_total{verrazzano_cluster=~\"$vzcluster\"}[$__rate_interval]\n  ) \n)",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(thanos_store_index_cache_hits_total{verrazzano_cluster=~\"$vzcluster\"}[5m])",
     "legendFormat": "{{item_type}} - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "bucket_store_cached_series_fetch_duration_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(thanos_bucket_store_cached_series_fetch_duration_seconds_count{verrazzano_cluster=~\"$vzcluster\"}[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}