{
 "title": "Coherence Services Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "vzcluster",
    "label": "Verrazzano Cluster",
    "query": "label_values(verrazzano_cluster)"
   },
   {
    "name": "ClusterName",
    "label": "Coherence Cluster",
    "query": "label_values(vendor:coherence_cluster_size{verrazzano_cluster=~\"$vzcluster\"}, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor:coherence_cluster_size{verrazzano_cluster=~\"$vzcluster\", cluster=~\"$ClusterName\"}, version)"
   },
   {
    "name": "Services",
    "label": "Services",
    "query": "label_values(vendor:coherence_service_request_max_duration{verrazzano_cluster=~\"$vzcluster\", cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "Caches",
    "label": "Caches",
    "query": "label_values(vendor:coherence_cache_size{verrazzano_cluster=~\"$vzcluster\", cluster=~\"$ClusterName\"}, name)"
   },
   { "name": "TopLimit", "label": "Top N Limit", "query": "1,3,5,10,15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Services Summary - Version: $CoherenceVersion</h3></center>"
  },
  {
   "title": "Storage Service List",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "avg(vendor:coherence_partition_assignment_service_node_count{verrazzano_cluster=~\"$vzcluster\", cluster=~\"$ClusterName\"}) by (verrazzano_cluster, coherence_service) "
    },
    {
     "expr": "avg(vendor:coherence_partition_assignment_ha_status_code{verrazzano_cluster=~\"$vzcluster\", cluster=~\"$ClusterName\"}) by (verrazzano_cluster, coherence_service)"
    }
   ]
  },
  {
   "title": "Non-Storage Service List",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "count(vendor:coherence_service_member_count{verrazzano_cluster=~\"$vzcluster\", cluster=~\"$ClusterName\",type!~\"DistributedCache|FederatedCache|ReplicatedCache\"}) by (verrazzano_cluster, name, type) "
    }
   ]
  },
  {
   "title": "Service Task Count - All Services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_service_task_count{verrazzano_cluster=~\"$vzcluster\", cluster=~\"$ClusterName\"}) - sum(vendor:coherence_service_task_count{verrazzano_cluster=~\"$vzcluster\", cluster=~\"$ClusterName\"} offset $__interval)",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Services With Endangered Partitions",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(vendor:coherence_service_partitions_endangered{verrazzano_cluster=~\"$vzcluster\", cluster=~\"$ClusterName\",type=~\"DistributedCache|FederatedCache\"}) by (verrazzano_cluster, name) > 0"
    }
   ]
  },
  {
   "title": "Services With Vulnerable Partitions",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "avg(vendor:coherence_service_partitions_vulnerable{verrazzano_cluster=~\"$vzcluster\", cluster=~\"$ClusterName\",type=~\"DistributedCache|FederatedCache\"}) by (verrazzano_cluster, name) > 0"
    }
   ]
  },
  {
   "title": "Services With Unbalanced Partitions",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "avg(vendor:coherence_service_partitions_unbalanced{verrazzano_cluster=~\"$vzcluster\", cluster=~\"$ClusterName\",type=~\"DistributedCache|FederatedCache\"}) by (verrazzano_cluster, name) > 0"
    }
   ]
  },
  {
   "title": "Top $TopLimit Services - Task Count  - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Services  that have the greatest change in the Task Count over the current time range.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": " topk($TopLimit,sum(delta(vendor:coherence_service_task_count{verrazzano_cluster=~\"$vzcluster\", cluster=~\"$ClusterName\"}[$__range])) by (verrazzano_cluster, name, member)) > 0"
    }
   ]
  },
  {
   "title": "Current Top $TopLimit Services - Task Backlog - Current Range",
   "type": "table",
   "description": "The Current top  $TopLimit Services  that have the greatest task backlog.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": " topk($TopLimit,sum(vendor:coherence_service_task_backlog{verrazzano_cluster=~\"$vzcluster\", cluster=~\"$ClusterName\"})  by (verrazzano_cluster, name, member)) > 0"
    }
   ]
  }
 ]
}