// Copyright (c) 2020, 2021, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

def DOCKER_IMAGE_TAG
def skipBuild = false

pipeline {
    options {
        skipDefaultCheckout true
        disableConcurrentBuilds()
    }

    agent {
       docker {
            image "${RUNNER_DOCKER_IMAGE}"
            args "${RUNNER_DOCKER_ARGS}"
            registryUrl "${RUNNER_DOCKER_REGISTRY_URL}"
            registryCredentialsId 'ocir-pull-and-push-account'
        }
    }

    parameters {
        string (name: 'ACCEPTANCE_TESTS_BRANCH',
                defaultValue: 'master',
                description: 'Branch or tag of verrazzano acceptance tests, on which to kick off the tests',
                trim: true
        )
        choice (description: 'OCI region to launch acceptance tests OKE clusters in', name: 'ACCEPTANCE_TESTS_OKE_REGION',
                // 1st choice is the default value
                choices: [ "us-ashburn-1", "ap-chuncheon-1", "ap-hyderabad-1", "ap-melbourne-1", "ap-mumbai-1", "ap-osaka-1", "ap-seoul-1", "ap-sydney-1",
                           "ap-tokyo-1", "ca-montreal-1", "ca-toronto-1", "eu-amsterdam-1", "eu-frankfurt-1", "eu-zurich-1", "me-jeddah-1",
                           "sa-saopaulo-1", "uk-london-1", "us-ashburn-1", "us-phoenix-1", "us-sanjose-1" ])
        booleanParam (description: 'Whether to kick off acceptance test run at the end of this build', name: 'RUN_ACCEPTANCE_TESTS', defaultValue: true)
    }


    environment {
        DOCKER_CI_IMAGE_NAME = 'verrazzano-application-operator-jenkins'
        DOCKER_PUBLISH_IMAGE_NAME = 'verrazzano-application-operator'
        DOCKER_IMAGE_NAME = "${env.BRANCH_NAME == 'master' ? env.DOCKER_PUBLISH_IMAGE_NAME : env.DOCKER_CI_IMAGE_NAME}"
        CREATE_LATEST_TAG = "${env.BRANCH_NAME == 'master' ? '1' : '0'}"
        GOPATH = '/home/opc/go'
        GO_REPO_PATH = "${GOPATH}/src/github.com/verrazzano"
        DOCKER_CREDS = credentials('github-packages-credentials-rw')
        DOCKER_REPO = 'ghcr.io'
        DOCKER_NAMESPACE = 'verrazzano'
        DOCKER_EMAIL = credentials('github-packages-email')
        NETRC_FILE = credentials('netrc')
        GITHUB_API_TOKEN = credentials('github-api-token-release-assets')
        GITHUB_RELEASE_USERID = credentials('github-userid-release')
        GITHUB_RELEASE_EMAIL = credentials('github-email-release')
        GHCR_REPO = 'ghcr.io'
        GITHUB_PKGS_CREDS = credentials('github-packages-credentials-rw')
        IMAGE_PULL_SECRET = 'github-packages'
        KUBECONFIG = "${HOME}/.kube/config"

    }

    stages {
        stage('Clean workspace and checkout') {
            steps {
                script {
                    checkout scm
                }
                sh """
                    cp -f "${NETRC_FILE}" $HOME/.netrc
                    chmod 600 $HOME/.netrc
                """

                sh """
                    echo "${DOCKER_CREDS_PSW}" | docker login ${env.DOCKER_REPO} -u ${DOCKER_CREDS_USR} --password-stdin
                    rm -rf ${GO_REPO_PATH}/verrazzano-application-operator
                    mkdir -p ${GO_REPO_PATH}/verrazzano-application-operator
                    tar cf - . | (cd ${GO_REPO_PATH}/verrazzano-application-operator/ ; tar xf -)
                """

                script {
                    def props = readProperties file: '.verrazzano-development-version'
                    VERRAZZANO_DEV_VERSION = props['verrazzano-development-version']
                    TIMESTAMP = sh(returnStdout: true, script: "date +%Y%m%d%H%M%S").trim()
                    SHORT_COMMIT_HASH = sh(returnStdout: true, script: "git rev-parse --short HEAD").trim()
                    DOCKER_IMAGE_TAG = "${VERRAZZANO_DEV_VERSION}-${TIMESTAMP}-${SHORT_COMMIT_HASH}"
                }
            }
        }

        stage('Build') {
            when {
                allOf {
                    not { buildingTag() }
                    equals expected: false, actual: skipBuild
                }
            }
            steps {
                sh """
                    cd ${GO_REPO_PATH}/verrazzano-application-operator
                    make docker-push DOCKER_REPO=${env.DOCKER_REPO} DOCKER_NAMESPACE=${env.DOCKER_NAMESPACE} DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME} DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG} CREATE_LATEST_TAG=${CREATE_LATEST_TAG}
                   """
            }
        }

        stage('gofmt Check') {
            when { not { buildingTag() } }
            steps {
                sh """
                    cd ${GO_REPO_PATH}/verrazzano-application-operator
                    make go-fmt
                """
            }
        }

        stage('go vet Check') {
            when { not { buildingTag() } }
            steps {
                sh """
                    cd ${GO_REPO_PATH}/verrazzano-application-operator
                    make go-vet
                """
            }
        }

        stage('golint Check') {
            when { not { buildingTag() } }
            steps {
                sh """
                    cd ${GO_REPO_PATH}/verrazzano-application-operator
                    make go-lint
                """
            }
        }

        stage('ineffassign Check') {
            when { not { buildingTag() } }
            steps {
                sh """
                    cd ${GO_REPO_PATH}/verrazzano-application-operator
                    make go-ineffassign
                """
            }
        }

        stage('Third Party License Check') {
            when {
                allOf {
                    not { buildingTag() }
                    equals expected: false, actual: skipBuild
                }
            }
            steps {
                thirdpartyCheck()
            }
        }

        stage('Copyright Compliance Check') {
            when {
                allOf {
                    not { buildingTag() }
                    equals expected: false, actual: skipBuild
                }
            }
            steps {
                copyrightScan "${WORKSPACE}"
            }
        }

        stage('Unit Tests') {
            when {
                allOf {
                    not { buildingTag() }
                    equals expected: false, actual: skipBuild
                }
            }
            steps {
                sh """
                    cd ${GO_REPO_PATH}/verrazzano-application-operator
                    make unit-test
                    make -B coverage
                    cp coverage.html ${WORKSPACE}
                    cp coverage.xml ${WORKSPACE}
                    build/scripts/copy-junit-output.sh ${WORKSPACE}
                """
            }
            post {
                always {
                    archiveArtifacts artifacts: '**/coverage.html', allowEmptyArchive: true
                    cobertura(coberturaReportFile: 'coverage.xml',
                      enableNewApi: false,
                      autoUpdateHealth: false,
                      autoUpdateStability: false,
                      failUnstable: false,
                      failUnhealthy: false,
                      failNoReports: false,
                      onlyStable: false,
                      conditionalCoverageTargets: '80, 0, 0',
                      fileCoverageTargets: '80, 0, 0',
                      lineCoverageTargets: '80, 0, 0',
                      packageCoverageTargets: '80, 0, 0',
                    )
                    junit testResults: '**/*test-result.xml', allowEmptyResults: true
                }
            }
        }

        stage('Scan Image') {
            when {
                allOf {
                    not { buildingTag() }
                    equals expected: false, actual: skipBuild
                }
            }
            steps {
                script {
                    clairScanTemp "${env.DOCKER_REPO}/${env.DOCKER_NAMESPACE}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
                }
            }
            post {
                always {
                    archiveArtifacts artifacts: '**/scanning-report.json', allowEmptyArchive: true
                }
            }
        }

        stage('Integration Tests') {
            when { not { buildingTag() } }
            steps {
                catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                    sh """
                    # Create the kind cluster
                    make create-cluster

                    # Create image pull secret for Verrazzano Docker images
                    cd ${GO_REPO_PATH}/verrazzano-application-operator
                    build/scripts/create-image-pull-secret.sh "${IMAGE_PULL_SECRET}" "${GHCR_REPO}" "${GITHUB_PKGS_CREDS_USR}" "${GITHUB_PKGS_CREDS_PSW}"

                    # Run the component integrations tests
                    make integ-test DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME} DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}
                    build/scripts/copy-junit-output.sh ${WORKSPACE}
                    """
                }
            }
            post {
                always {
                    sh "cat /home/opc/go/src/github.com/verrazzano/verrazzano-application-operator/installer/build/logs/install.sh.log"
                    archiveArtifacts artifacts: '**/logs/**', allowEmptyArchive: true
                    junit testResults: '**/*test-result.xml', allowEmptyResults: true
                }
            }
        }

        stage('Write image name to application-operator.txt') {
            when {
                allOf {
                    not { buildingTag() }
                    anyOf { branch 'master' }
                }
            }
            steps {
                sh """
                    cd ${GO_REPO_PATH}/verrazzano-application-operator
                    echo ${env.DOCKER_REPO}/${env.DOCKER_NAMESPACE}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} > deploy/application-operator.txt
                    cat deploy/application-operator.txt
                    git config --global credential.helper "!f() { echo username=\\$DOCKER_CREDS_USR; echo password=\\$DOCKER_CREDS_PSW; }; f"
                    git config --global user.name $DOCKER_CREDS_USR
                    git config --global user.email "${DOCKER_EMAIL}"
                    git checkout -b ${env.BRANCH_NAME}
                    git add deploy/application-operator.txt
                    git commit -m "[verrazzano] Update verrazzano-application-operator image version to ${DOCKER_IMAGE_TAG} in application-operator.txt"
                    git push origin ${env.BRANCH_NAME}
                   """
            }
        }

        stage('Kick off KinD Acceptance tests') {
            when {
                allOf {
                    not { buildingTag() }
                    anyOf {
                        expression { return params.RUN_ACCEPTANCE_TESTS == true }
                    }
                }
            }
            environment {
                FULL_IMAGE_NAME = "${env.DOCKER_REPO}/${env.DOCKER_NAMESPACE}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
            }
            steps {
                sh """
                    echo "using ACCEPTANCE_TESTS_BRANCH=${params.ACCEPTANCE_TESTS_BRANCH}"
                    echo "using APP_OPERATOR_IMAGE=${FULL_IMAGE_NAME}"
                """
                build job: "verrazzano-app-operator-acceptest/${env.BRANCH_NAME.replace("/", "%2F")}",
                        parameters: [string(name: 'APPLICATION_OPERATOR_BRANCH', value: env.BRANCH_NAME),
                                     string(name: 'APPLICATION_OPERATOR_IMAGE', value: FULL_IMAGE_NAME),
                                     string(name: 'ACCEPTANCE_TESTS_BRANCH', value: params.ACCEPTANCE_TESTS_BRANCH),
                                     string(name: 'TEST_ENV', value: 'kind'),
                                     string(name: 'INSTALL_PROFILE', value: 'dev')],
                        wait: false,
                        propagate: true
            }
        }
    }

    post {
        failure {
            mail to: "${env.BUILD_NOTIFICATION_TO_EMAIL}", from: "${env.BUILD_NOTIFICATION_FROM_EMAIL}",
            subject: "Verrazzano: ${env.JOB_NAME} - Failed",
            body: "Job Failed - \"${env.JOB_NAME}\" build: ${env.BUILD_NUMBER}\n\nView the log at:\n ${env.BUILD_URL}\n\nBlue Ocean:\n${env.RUN_DISPLAY_URL}"
        }
    }
}
