{
 "title": "OpenSearch Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Cluster Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "es_cluster_status{cluster=\"system\"}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "es_cluster_nodes_number{verrazzano_cluster=\"local\"}"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "es_cluster_datanodes_number{verrazzano_cluster=\"local\"}"
    }
   ]
  },
  {
   "title": "Index Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(es_index_replicas_number{verrazzano_cluster=\"local\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "es_cluster_pending_tasks_number{verrazzano_cluster=\"local\"}"
    }
   ]
  },
  { "title": "Shard Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Active Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(es_cluster_shards_number{cluster=\"system\", type=\"active\"})"
    }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(es_cluster_shards_number{cluster=\"system\", type=\"active_primary\"})"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(es_cluster_shards_number{cluster=\"system\", type=\"relocating\"})"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(es_cluster_shards_number{cluster=\"system\", type=\"initializing\"})"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(es_cluster_shards_number{cluster=\"system\", type=\"unassigned\"})"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Index Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(es_index_replicas_number{cluster=\"system\"})"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "es_indices_store_size_bytes{cluster=\"system\"}"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(es_indices_merges_total_docs_count{cluster=\"system\"})"
    }
   ]
  },
  {
   "title": "Documents Index Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(es_indices_indexing_index_count{cluster=\"system\"}[1h])"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "es_process_file_descriptors_max_number{cluster=\"system\"}"
    }
   ]
  },
  {
   "title": "Shards Per Index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(es_index_shards_number{cluster=\"system\",type=\"active\"}) by (index)"
    }
   ]
  },
  {
   "title": "Disk Watermark %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (es_fs_path_available_bytes /es_fs_path_total_bytes))* 100",
     "legendFormat": "current_disk_watermark"
    },
    {
     "expr": "es_cluster_routing_allocation_disk_watermark_low_pct{cluster=\"system\"}",
     "legendFormat": "disk_watermark_low_pct"
    },
    {
     "expr": "es_cluster_routing_allocation_disk_watermark_high_pct{cluster=\"system\"}",
     "legendFormat": "disk_watermark_high_pct"
    },
    {
     "expr": "es_cluster_routing_allocation_disk_watermark_flood_stage_pct{cluster=\"system\"}",
     "legendFormat": "disk_watermark_flood_stage_pct"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(es_indices_search_fetch_count{cluster=\"system\"}[1h])"
    }
   ]
  }
 ]
}