// Copyright (c) 2020, 2023, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/verrazzano/verrazzano/platform-operator/clientset/versioned/typed/platform/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakePlatformV1alpha1 struct {
	*testing.Fake
}

func (c *FakePlatformV1alpha1) Modules(namespace string) v1alpha1.ModuleInterface {
	return &FakeModules{c, namespace}
}

func (c *FakePlatformV1alpha1) ModuleDefinitions() v1alpha1.ModuleDefinitionInterface {
	return &FakeModuleDefinitions{c}
}

func (c *FakePlatformV1alpha1) OperatorDefinitions() v1alpha1.OperatorDefinitionInterface {
	return &FakeOperatorDefinitions{c}
}

func (c *FakePlatformV1alpha1) Platforms(namespace string) v1alpha1.PlatformInterface {
	return &FakePlatforms{c, namespace}
}

func (c *FakePlatformV1alpha1) PlatformDefinitions(namespace string) v1alpha1.PlatformDefinitionInterface {
	return &FakePlatformDefinitions{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakePlatformV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
