// Copyright (c) 2021, 2022, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/verrazzano/verrazzano/image-patch-operator/api/images/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeImageBuildRequests implements ImageBuildRequestInterface
type FakeImageBuildRequests struct {
	Fake *FakeImagesV1alpha1
	ns   string
}

var imagebuildrequestsResource = schema.GroupVersionResource{Group: "images", Version: "v1alpha1", Resource: "imagebuildrequests"}

var imagebuildrequestsKind = schema.GroupVersionKind{Group: "images", Version: "v1alpha1", Kind: "ImageBuildRequest"}

// Get takes name of the imageBuildRequest, and returns the corresponding imageBuildRequest object, and an error if there is any.
func (c *FakeImageBuildRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ImageBuildRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(imagebuildrequestsResource, c.ns, name), &v1alpha1.ImageBuildRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageBuildRequest), err
}

// List takes label and field selectors, and returns the list of ImageBuildRequests that match those selectors.
func (c *FakeImageBuildRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ImageBuildRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(imagebuildrequestsResource, imagebuildrequestsKind, c.ns, opts), &v1alpha1.ImageBuildRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ImageBuildRequestList{ListMeta: obj.(*v1alpha1.ImageBuildRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.ImageBuildRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested imageBuildRequests.
func (c *FakeImageBuildRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(imagebuildrequestsResource, c.ns, opts))

}

// Create takes the representation of a imageBuildRequest and creates it.  Returns the server's representation of the imageBuildRequest, and an error, if there is any.
func (c *FakeImageBuildRequests) Create(ctx context.Context, imageBuildRequest *v1alpha1.ImageBuildRequest, opts v1.CreateOptions) (result *v1alpha1.ImageBuildRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(imagebuildrequestsResource, c.ns, imageBuildRequest), &v1alpha1.ImageBuildRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageBuildRequest), err
}

// Update takes the representation of a imageBuildRequest and updates it. Returns the server's representation of the imageBuildRequest, and an error, if there is any.
func (c *FakeImageBuildRequests) Update(ctx context.Context, imageBuildRequest *v1alpha1.ImageBuildRequest, opts v1.UpdateOptions) (result *v1alpha1.ImageBuildRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(imagebuildrequestsResource, c.ns, imageBuildRequest), &v1alpha1.ImageBuildRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageBuildRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeImageBuildRequests) UpdateStatus(ctx context.Context, imageBuildRequest *v1alpha1.ImageBuildRequest, opts v1.UpdateOptions) (*v1alpha1.ImageBuildRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(imagebuildrequestsResource, "status", c.ns, imageBuildRequest), &v1alpha1.ImageBuildRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageBuildRequest), err
}

// Delete takes name of the imageBuildRequest and deletes it. Returns an error if one occurs.
func (c *FakeImageBuildRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(imagebuildrequestsResource, c.ns, name, opts), &v1alpha1.ImageBuildRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeImageBuildRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(imagebuildrequestsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ImageBuildRequestList{})
	return err
}

// Patch applies the patch and returns the patched imageBuildRequest.
func (c *FakeImageBuildRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ImageBuildRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(imagebuildrequestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ImageBuildRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageBuildRequest), err
}
