{
 "title": "System Health",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Available Components",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpo_component_health_count" }
   ]
  },
  {
   "title": "Number of Enabled Components",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpo_component_enabled_count" }
   ]
  },
  {
   "title": "Component Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vpo_component_health_count/vpo_component_enabled_count)*100"
    }
   ]
  },
  {
   "title": "Component Availability ",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpo_component_health", "legendFormat": "{{component}}" }
   ]
  }
 ]
}