{
 "title": "Application Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "vzcluster",
    "label": "Verrazzano Cluster",
    "query": {
     "query": "label_values(verrazzano_cluster)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(up{verrazzano_cluster=~\"$vzcluster\"}, app_oam_dev_name)"
    }
   },
   {
    "name": "component",
    "query": {
     "query": "label_values(up{verrazzano_cluster=~\"$vzcluster\", app_oam_dev_name=\"$application\"}, app_oam_dev_component)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Component CPU Usage (cores)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=~\".+\"} and on (pod) \nkube_pod_labels{verrazzano_cluster=~\"$vzcluster\", label_app_oam_dev_name != \"\", label_app_oam_dev_name=\"$application\", label_app_oam_dev_component=~\"$component\"})\n",
     "legendFormat": "$component"
    }
   ]
  },
  {
   "title": "Component Memory Usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(max(container_memory_working_set_bytes{verrazzano_cluster=~\"$vzcluster\", container!=\"\", image!=\"\"}  and on (pod)\nkube_pod_labels{verrazzano_cluster=~\"$vzcluster\", label_app_oam_dev_name != \"\", label_app_oam_dev_name=\"$application\",label_app_oam_dev_component=~\"$component\"}) by (container))",
     "legendFormat": "$component"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_info and on (pod)\nkube_pod_labels{verrazzano_cluster=\"$vzcluster\", label_app_oam_dev_name != \"\", label_app_oam_dev_name=\"$application\", label_app_oam_dev_component=~\"$component\"}"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate and on (pod)\nkube_pod_labels{verrazzano_cluster=\"$vzcluster\", label_app_oam_dev_name != \"\", label_app_oam_dev_name=\"$application\", label_app_oam_dev_component=~\"$component\"}) by (pod)"
    },
    {
     "expr": "sum(max(container_memory_working_set_bytes{container!=\"\", image!=\"\"} and on (pod)\nkube_pod_labels{verrazzano_cluster=\"$vzcluster\", label_app_oam_dev_name != \"\", label_app_oam_dev_name=\"$application\", label_app_oam_dev_component=~\"$component\"}) by (container, pod)) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total and on (pod)\nkube_pod_labels{verrazzano_cluster=\"$vzcluster\", label_app_oam_dev_name != \"\", label_app_oam_dev_name=\"$application\", label_app_oam_dev_component=~\"$component\"}) by (pod)"
    },
    {
     "expr": "max(kube_pod_status_ready{condition=\"true\"} and on (pod)\nkube_pod_labels{verrazzano_cluster=\"$vzcluster\", label_app_oam_dev_name != \"\", label_app_oam_dev_name=\"$application\", label_app_oam_dev_component=~\"$component\"}) by (pod)"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "HTTP Requests/second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{verrazzano_cluster=~\"$vzcluster\"}[1m]) and on (destination_service_name) label_replace(kube_service_labels{verrazzano_cluster=~\"$vzcluster\", label_app_oam_dev_name != \"\", label_app_oam_dev_name=\"$application\",label_app_oam_dev_component=~\"$component\"}, \"destination_service_name\", \"$1\", \"service\", \"(.+)\"))",
     "legendFormat": "$component"
    }
   ]
  },
  {
   "title": "5xx Response Rate",
   "type": "graph",
   "description": "Total Requests per second divided by Requests with 5xx responses per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(rate(istio_requests_total{verrazzano_cluster=~\"$vzcluster\", response_code=~\"5.*\"}[1m]) and on (destination_service_name) label_replace(kube_service_labels{verrazzano_cluster=~\"$vzcluster\", label_app_oam_dev_name != \"\", label_app_oam_dev_name=\"$application\",label_app_oam_dev_component=~\"$component\"}, \"destination_service_name\", \"$1\", \"service\", \"(.+)\")) / sum(rate(istio_requests_total{verrazzano_cluster=~\"$vzcluster\"}[1m]) and on (destination_service_name) label_replace(kube_service_labels{verrazzano_cluster=~\"$vzcluster\", label_app_oam_dev_name != \"\", label_app_oam_dev_name=\"$application\",label_app_oam_dev_component=~\"$component\"}, \"destination_service_name\", \"$1\", \"service\", \"(.+)\"))",
     "legendFormat": "$component"
    }
   ]
  },
  {
   "title": "Avg Request Duration (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_request_duration_milliseconds_sum{verrazzano_cluster=~\"$vzcluster\"} and on (destination_service_name) label_replace(kube_service_labels{verrazzano_cluster=~\"$vzcluster\", label_app_oam_dev_name != \"\", label_app_oam_dev_name=\"$application\",label_app_oam_dev_component=~\"$component\"}, \"destination_service_name\", \"$1\", \"service\", \"(.+)\")) / sum(istio_request_duration_milliseconds_count{verrazzano_cluster=~\"$vzcluster\"} and on (destination_service_name) label_replace(kube_service_labels{verrazzano_cluster=~\"$vzcluster\", label_app_oam_dev_name != \"\", label_app_oam_dev_name=\"$application\",label_app_oam_dev_component=~\"$component\"}, \"destination_service_name\", \"$1\", \"service\", \"(.+)\"))",
     "legendFormat": "$component"
    }
   ]
  }
 ]
}