{
 "title": "Cluster Resource Usage",
 "description": "Resource usage for all nodes of a cluster",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up, verrazzano_cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{verrazzano_cluster=\"$cluster\", mode!=\"idle\"}[5m]))",
     "legendFormat": "cluster $cluster"
    }
   ]
  },
  {
   "title": "CPU Utilization Percentage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{verrazzano_cluster=\"$cluster\", mode!=\"idle\"}[5m])) / on() group_right() count(max(node_cpu_seconds_total{verrazzano_cluster=\"$cluster\"}) by (verrazzano_cluster, cpu)) by (verrazzano_cluster) "
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{verrazzano_cluster=\"$cluster\", mode!=\"idle\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Max",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(node_cpu_seconds_total{verrazzano_cluster=\"$cluster\"}) by (verrazzano_cluster, cpu)) by (verrazzano_cluster) "
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{verrazzano_cluster=\"$cluster\"} - node_memory_Active_bytes{verrazzano_cluster=\"$cluster\"}) by (verrazzano_cluster)",
     "legendFormat": "cluster $cluster"
    }
   ]
  },
  {
   "title": "Memory Utilization Percentage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_Active_bytes{verrazzano_cluster=\"$cluster\"}) by (verrazzano_cluster) / sum(node_memory_MemTotal_bytes{verrazzano_cluster=\"$cluster\"}) by (verrazzano_cluster)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_Active_bytes{verrazzano_cluster=\"$cluster\"}) by (verrazzano_cluster)",
     "legendFormat": "cluster $cluster"
    }
   ]
  },
  {
   "title": "Memory Max",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{verrazzano_cluster=\"$cluster\"}) by (verrazzano_cluster)"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Storage Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(max(node_filesystem_size_bytes{verrazzano_cluster=\"$cluster\"}) by (device) - max(node_filesystem_avail_bytes{verrazzano_cluster=\"$cluster\"}) by (device)) by (verrazzano_cluster)",
     "legendFormat": "cluster $cluster"
    }
   ]
  },
  {
   "title": "Storage Utilization Percentage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(node_filesystem_size_bytes{verrazzano_cluster=\"$cluster\"}) by (device) - max(node_filesystem_avail_bytes{verrazzano_cluster=\"$cluster\"}) by (device)) by (verrazzano_cluster) / sum(max(node_filesystem_size_bytes{verrazzano_cluster=\"$cluster\"}) by (device)) by (verrazzano_cluster)"
    }
   ]
  },
  {
   "title": "Storage Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(node_filesystem_size_bytes{verrazzano_cluster=\"$cluster\"}) by (device) - max(node_filesystem_avail_bytes{verrazzano_cluster=\"$cluster\"}) by (device)) by (verrazzano_cluster)"
    }
   ]
  },
  {
   "title": "Storage Max",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(node_filesystem_size_bytes{verrazzano_cluster=\"$cluster\"}) by (device)) by (verrazzano_cluster)"
    }
   ]
  }
 ]
}