{
 "title": "Resource Usage Detailed",
 "tags": [ "vz_resource_usage_detailed" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Verrazzano Cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, verrazzano_cluster)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{verrazzano_cluster=\"$cluster\"},verrazzano_component)"
    }
   },
   {
    "name": "available_pvc",
    "query": {
     "query": "query_result(round(sum(kube_pod_spec_volumes_persistentvolumeclaims_info{verrazzano_component != \"\"} * on(persistentvolumeclaim, namespace) group_right(verrazzano_component) kubelet_volume_stats_available_bytes{verrazzano_cluster=\"$cluster\"}  )/1024/1024/1024,0.01))"
    }
   },
   {
    "name": "available_cpu",
    "query": {
     "query": "query_result(round(sum (count without (cpu, mode) (node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",verrazzano_cluster=\"$cluster\"}) - ((1 - avg without (cpu) (sum without (mode) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=~\"idle|iowait|steal\",verrazzano_cluster=\"$cluster\"}[5m])))) * count without (cpu, mode) (node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",verrazzano_cluster=\"$cluster\"}))),0.01))"
    }
   },
   {
    "name": "available_memory",
    "query": {
     "query": "query_result(round(sum(node_memory_MemAvailable_bytes{job=\"node-exporter\",verrazzano_cluster=\"$cluster\"} or (node_memory_Buffers_bytes{job=\"node-exporter\",verrazzano_cluster=\"$cluster\"} + node_memory_Cached_bytes{job=\"node-exporter\",verrazzano_cluster=\"$cluster\"} + node_memory_MemFree_bytes{job=\"node-exporter\",verrazzano_cluster=\"$cluster\"} + node_memory_Slab_bytes{job=\"node-exporter\",verrazzano_cluster=\"$cluster\"}))/1024/1024/1024,0.01))"
    }
   },
   {
    "name": "available_storage",
    "query": {
     "query": "query_result(round(sum(node_filesystem_avail_bytes{mountpoint=\"/\", verrazzano_cluster=\"$cluster\"})/1024/1024/1024,0.01))"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{verrazzano_cluster=\"$cluster\",verrazzano_component=~\"$component\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{verrazzano_cluster=\"$cluster\",verrazzano_component=~\"$component\",namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$component", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "component" },
  {
   "title": "CPU(Available: $available_cpu)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (verrazzano_component, namespace, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory(Available: $available_memory GiB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (verrazzano_component, namespace, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Storage(Available: $available_storage GiB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (verrazzano_component, namespace, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVC Usage(Available: $available_pvc GiB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_spec_volumes_persistentvolumeclaims_info{verrazzano_component=~\"$component\", namespace=~\"$namespace\", pod=~\"$pod\"} * on(persistentvolumeclaim, namespace) group_right(verrazzano_component) kubelet_volume_stats_used_bytes{verrazzano_cluster=\"$cluster\", namespace=~\"$namespace\"}  ) by (verrazzano_component, persistentvolumeclaim, namespace, pod)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}