{
 "title": "Resource Usage Summary",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Verrazzano Cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, verrazzano_cluster)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{verrazzano_cluster=\"$cluster\"},verrazzano_component)"
    }
   },
   {
    "name": "used_cpu",
    "query": {
     "query": "query_result(round(sum((sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=~\".+\"}) by (pod))* on(pod) group_right kube_pod_labels{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}),0.01))"
    }
   },
   {
    "name": "used_memory",
    "query": {
     "query": "query_result(round(sum(node_namespace_pod_container:container_memory_working_set_bytes{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"})/1024/1024/1024,0.01))"
    }
   },
   {
    "name": "used_storage",
    "query": {
     "query": "query_result(round(sum(container_fs_usage_bytes{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"})/1024/1024/1024,0.01))"
    }
   },
   {
    "name": "used_pvc",
    "query": {
     "query": "query_result(round(sum(kube_pod_spec_volumes_persistentvolumeclaims_info{verrazzano_component=~\"$component\",verrazzano_cluster=\"$cluster\"} * on(persistentvolumeclaim, namespace) group_right(verrazzano_component) kubelet_volume_stats_used_bytes{verrazzano_cluster=\"$cluster\"})/1024/1024/1024,0.01))"
    }
   },
   {
    "name": "available_pvc",
    "query": {
     "query": "query_result(round(sum(kube_pod_spec_volumes_persistentvolumeclaims_info{verrazzano_component=~\"$component\",verrazzano_cluster=\"$cluster\"} * on(persistentvolumeclaim, namespace) group_right(verrazzano_component) kubelet_volume_stats_available_bytes{verrazzano_cluster=\"$cluster\"})/1024/1024/1024,0.01))"
    }
   },
   {
    "name": "available_cpu",
    "query": {
     "query": "query_result(round(sum (count without (cpu, mode) (node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",verrazzano_cluster=\"$cluster\"}) - ((1 - avg without (cpu) (sum without (mode) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=~\"idle|iowait|steal\",verrazzano_cluster=\"$cluster\"}[5m])))) * count without (cpu, mode) (node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",verrazzano_cluster=\"$cluster\"}))),0.01))"
    }
   },
   {
    "name": "available_memory",
    "query": {
     "query": "query_result(round(sum(node_memory_MemAvailable_bytes{job=\"node-exporter\",verrazzano_cluster=\"$cluster\"} or (node_memory_Buffers_bytes{job=\"node-exporter\",verrazzano_cluster=\"$cluster\"} + node_memory_Cached_bytes{job=\"node-exporter\",verrazzano_cluster=\"$cluster\"} + node_memory_MemFree_bytes{job=\"node-exporter\",verrazzano_cluster=\"$cluster\"} + node_memory_Slab_bytes{job=\"node-exporter\",verrazzano_cluster=\"$cluster\"}))/1024/1024/1024,0.01))"
    }
   },
   {
    "name": "available_storage",
    "query": {
     "query": "query_result(round(sum(node_filesystem_avail_bytes{mountpoint=\"/\", verrazzano_cluster=\"$cluster\"})/1024/1024/1024,0.01))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU(Used: $used_cpu cores, Available: $available_cpu cores)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=~\".+\"}) by (pod))* on(pod) group_right kube_pod_labels{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (verrazzano_component)",
     "legendFormat": "{{verrazzano_component}}"
    }
   ]
  },
  {
   "title": "Memory(Used: $used_memory GiB, Available: $available_memory GiB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (verrazzano_component)",
     "legendFormat": "{{verrazzzano_component}}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_info{verrazzano_cluster=\"$cluster\"} and on (pod)\nkube_pod_labels{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=~\".+\"} and on (pod)\nkube_pod_labels{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (pod)"
    },
    {
     "expr": "max(kube_pod_status_ready{condition=\"true\",verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (pod)"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Disk(Used: $used_storage GiB, Available: $available_storage GiB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (verrazzano_component)",
     "legendFormat": "{{verrazzzano_component}}"
    }
   ]
  },
  {
   "title": "PVC(Used: $used_pvc GiB, Available: $available_pvc GiB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(kube_pod_spec_volumes_persistentvolumeclaims_info{verrazzano_component=~\"$component\",verrazzano_cluster=\"$cluster\"}) by(persistentvolumeclaim, namespace, verrazzano_component, verrazzano_cluster) * on(persistentvolumeclaim, namespace) group_right(verrazzano_component) kubelet_volume_stats_used_bytes{verrazzano_cluster=\"$cluster\"}) by (verrazzano_component)",
     "legendFormat": "{{verrazzzano_component}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "HTTP Requests/second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(label_replace(irate(istio_requests_total{verrazzano_cluster=\"$cluster\"}[$__rate_interval]), \"service\", \"$1\", \"destination_service_name\", \"(.+)}\") and on(service) up{verrazzano_cluster=\"$cluster\"} and on(namespace, pod) kube_pod_labels{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (verrazzano_cluster, namespace, pod) * on(verrazzano_cluster, namespace, pod) group_right kube_pod_labels{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"})by(verrazzano_component)",
     "legendFormat": "{{verrazzano_component}}"
    }
   ]
  },
  {
   "title": "5xx Response Rate",
   "type": "graph",
   "description": "Requests with 5xx responses per second divided by Total Requests per second ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * round(sum(sum(label_replace(rate(istio_requests_total{verrazzano_cluster=\"$cluster\",response_code=~\"5.*\"}[$__rate_interval]), \"service\", \"$1\", \"destination_service_name\", \"(.+)}\") and on(service) up{verrazzano_cluster=\"$cluster\"} and on(namespace, pod) kube_pod_labels{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (verrazzano_cluster, namespace, pod) * on(verrazzano_cluster, namespace, pod) group_right kube_pod_labels{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (verrazzano_component)/ sum(sum(label_replace(rate(istio_requests_total{verrazzano_cluster=\"$cluster\"}[$__rate_interval]), \"service\", \"$1\", \"destination_service_name\", \"(.+)}\") and on(service) up{verrazzano_cluster=\"$cluster\"} and on(namespace, pod) kube_pod_labels{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (verrazzano_cluster, namespace, pod) * on(verrazzano_cluster, namespace, pod) group_right kube_pod_labels{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (verrazzano_component), 0.01)",
     "legendFormat": "{{verrazzano_component}}"
    }
   ]
  },
  {
   "title": "Avg Request Duration (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(sum(label_replace(istio_request_duration_milliseconds_sum{verrazzano_cluster=\"$cluster\"}, \"service\", \"$1\", \"destination_service_name\", \"(.+)}\") and on(service) up{verrazzano_cluster=\"$cluster\"} and on(namespace, pod) kube_pod_labels{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (verrazzano_cluster, namespace, pod) * on(verrazzano_cluster, namespace, pod) group_right kube_pod_labels{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (verrazzano_component)/ sum(sum(label_replace(istio_request_duration_milliseconds_count{verrazzano_cluster=\"$cluster\"}, \"service\", \"$1\", \"destination_service_name\", \"(.+)}\") and on(service) up{verrazzano_cluster=\"$cluster\"} and on(namespace, pod) kube_pod_labels{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (verrazzano_cluster, namespace, pod) * on(verrazzano_cluster, namespace, pod) group_right kube_pod_labels{verrazzano_cluster=\"$cluster\", verrazzano_component=~\"$component\"}) by (verrazzano_component), 0.01)",
     "legendFormat": "{{verrazzano_component}}"
    }
   ]
  }
 ]
}