{
 "title": "System Health",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vzcluster",
    "label": "Verrazzano Cluster",
    "query": {
     "query": "label_values(verrazzano_cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Available Components",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vz_platform_operator_component_health_total{verrazzano_cluster=\"$vzcluster\"}"
    }
   ]
  },
  {
   "title": "Number of Enabled Components",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vz_platform_operator_component_enabled_total{verrazzano_cluster=\"$vzcluster\"}"
    }
   ]
  },
  {
   "title": "Component Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vz_platform_operator_component_health_total{verrazzano_cluster=\"$vzcluster\"}/vz_platform_operator_component_enabled_total{verrazzano_cluster=\"$vzcluster\"}"
    }
   ]
  },
  {
   "title": "Component Availability ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "vz_platform_operator_component_health{verrazzano_cluster=\"$vzcluster\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"DiskPressure\", status=\"false\", verrazzano_cluster=\"$vzcluster\"}"
    },
    {
     "expr": "kube_node_status_condition{condition=\"MemoryPressure\", status=\"false\", verrazzano_cluster=\"$vzcluster\"}"
    },
    {
     "expr": "kube_node_status_condition{condition=\"PIDPressure\", status=\"false\", verrazzano_cluster=\"$vzcluster\"}"
    },
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\", verrazzano_cluster=\"$vzcluster\"}"
    }
   ]
  }
 ]
}