{
 "title": "Helidon Monitoring Dashboard",
 "description": "Helidon Endpoint Metrics Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vzcluster",
    "label": "Verrazzano Cluster",
    "query": {
     "query": "label_values(verrazzano_cluster)"
    }
   },
   {
    "name": "serviceID",
    "label": "ServiceID",
    "query": {
     "query": "label_values(base_classloader_loadedClasses_count{verrazzano_cluster=~\"$vzcluster\"}, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(base_classloader_loadedClasses_count{verrazzano_cluster=~\"$vzcluster\",job=\"$serviceID\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"$serviceID\", instance=\"$instance\",verrazzano_cluster=~\"$vzcluster\",container!~\"istio-proxy|jaeger-agent|fluentd-stdout-sidecar\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": " base_jvm_uptime_seconds Displays the uptime of the JVM in milliseconds.",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{instance=\"$instance\", job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\",container!~\"istio-proxy|jaeger-agent|fluentd-stdout-sidecar\"}"
    }
   ]
  },
  {
   "title": "GC Copy & Mark Sweep Total",
   "type": "graph",
   "description": "base_gc_total Displays the total number of collections that have occurred. This attribute lists -1 if the collection count is undefined for this collector.",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_gc_total{instance=\"$instance\", job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "GC Copy & Mark Sweep Time",
   "type": "graph",
   "description": "base_gc_time_seconds Displays the approximate accumulated collection elapsed time in seconds. This attribute displays -1 if the collection elapsed time is undefined for this collector. The JVM implementation may use a high resolution timer to measure the elapsed time. This attribute may display the same value even if the collection count has been incremented if the collection elapsed time is very short.",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "base_gc_time_seconds{instance=\"$instance\", job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "base_cpu_systemLoadAverage{instance=\"$instance\",job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\"}",
     "legendFormat": "CPU load"
    }
   ]
  },
  {
   "title": "Heap Sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{instance=\"$instance\",job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\"}",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "base_memory_committedHeap_bytes{instance=\"$instance\", job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\", }",
     "legendFormat": "Commited Heap"
    },
    {
     "expr": "base_memory_maxHeap_bytes{instance=\"$instance\", job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\"}",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{instance=\"$instance\",job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\"}",
     "legendFormat": "Thread Count"
    }
   ]
  },
  {
   "title": "Currently loaded Classes",
   "type": "singlestat",
   "description": "base_classloader_loadedClasses_count Displays the number of classes that are currently loaded in the JVM.",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_count{instance=\"$instance\", job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\",container!~\"istio-proxy|jaeger-agent|fluentd-stdout-sidecar\"}"
    }
   ]
  },
  {
   "title": "Total loaded Classes",
   "type": "singlestat",
   "description": "base_classloader_loadedClasses_total_total Displays the total number of classes that have been loaded since the JVM has started execution.",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_total_total{instance=\"$instance\", job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\",container!~\"istio-proxy|jaeger-agent|fluentd-stdout-sidecar\"}"
    }
   ]
  },
  {
   "title": "Total unloaded Classes",
   "type": "singlestat",
   "description": "base_classloader_unloadedClasses_total_total Displays the total number of classes unloaded since the JVM has started execution.",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "base_classloader_unloadedClasses_total_total{instance=\"$instance\", job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\",container!~\"istio-proxy|jaeger-agent|fluentd-stdout-sidecar\"}"
    }
   ]
  },
  {
   "title": "HTTP requests_meter_rate_per_second",
   "type": "graph",
   "description": "vendor_requests_meter_rate_per_second",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_requests_meter_rate_per_second{instance=\"$instance\", job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\"}"
    }
   ]
  },
  {
   "title": "GRPC requests_meter_rate_per_second",
   "type": "graph",
   "description": "vendor_grpc_requests_meter_rate_per_second",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_grpc_requests_meter_rate_per_second{instance=\"$instance\", job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\"}"
    }
   ]
  }
 ]
}