// Copyright (c) 2021, 2022, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/verrazzano/verrazzano/application-operator/apis/oam/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVerrazzanoCoherenceWorkloads implements VerrazzanoCoherenceWorkloadInterface
type FakeVerrazzanoCoherenceWorkloads struct {
	Fake *FakeOamV1alpha1
	ns   string
}

var verrazzanocoherenceworkloadsResource = schema.GroupVersionResource{Group: "oam.verrazzano.io", Version: "v1alpha1", Resource: "verrazzanocoherenceworkloads"}

var verrazzanocoherenceworkloadsKind = schema.GroupVersionKind{Group: "oam.verrazzano.io", Version: "v1alpha1", Kind: "VerrazzanoCoherenceWorkload"}

// Get takes name of the verrazzanoCoherenceWorkload, and returns the corresponding verrazzanoCoherenceWorkload object, and an error if there is any.
func (c *FakeVerrazzanoCoherenceWorkloads) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VerrazzanoCoherenceWorkload, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(verrazzanocoherenceworkloadsResource, c.ns, name), &v1alpha1.VerrazzanoCoherenceWorkload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VerrazzanoCoherenceWorkload), err
}

// List takes label and field selectors, and returns the list of VerrazzanoCoherenceWorkloads that match those selectors.
func (c *FakeVerrazzanoCoherenceWorkloads) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VerrazzanoCoherenceWorkloadList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(verrazzanocoherenceworkloadsResource, verrazzanocoherenceworkloadsKind, c.ns, opts), &v1alpha1.VerrazzanoCoherenceWorkloadList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VerrazzanoCoherenceWorkloadList{ListMeta: obj.(*v1alpha1.VerrazzanoCoherenceWorkloadList).ListMeta}
	for _, item := range obj.(*v1alpha1.VerrazzanoCoherenceWorkloadList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested verrazzanoCoherenceWorkloads.
func (c *FakeVerrazzanoCoherenceWorkloads) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(verrazzanocoherenceworkloadsResource, c.ns, opts))

}

// Create takes the representation of a verrazzanoCoherenceWorkload and creates it.  Returns the server's representation of the verrazzanoCoherenceWorkload, and an error, if there is any.
func (c *FakeVerrazzanoCoherenceWorkloads) Create(ctx context.Context, verrazzanoCoherenceWorkload *v1alpha1.VerrazzanoCoherenceWorkload, opts v1.CreateOptions) (result *v1alpha1.VerrazzanoCoherenceWorkload, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(verrazzanocoherenceworkloadsResource, c.ns, verrazzanoCoherenceWorkload), &v1alpha1.VerrazzanoCoherenceWorkload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VerrazzanoCoherenceWorkload), err
}

// Update takes the representation of a verrazzanoCoherenceWorkload and updates it. Returns the server's representation of the verrazzanoCoherenceWorkload, and an error, if there is any.
func (c *FakeVerrazzanoCoherenceWorkloads) Update(ctx context.Context, verrazzanoCoherenceWorkload *v1alpha1.VerrazzanoCoherenceWorkload, opts v1.UpdateOptions) (result *v1alpha1.VerrazzanoCoherenceWorkload, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(verrazzanocoherenceworkloadsResource, c.ns, verrazzanoCoherenceWorkload), &v1alpha1.VerrazzanoCoherenceWorkload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VerrazzanoCoherenceWorkload), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVerrazzanoCoherenceWorkloads) UpdateStatus(ctx context.Context, verrazzanoCoherenceWorkload *v1alpha1.VerrazzanoCoherenceWorkload, opts v1.UpdateOptions) (*v1alpha1.VerrazzanoCoherenceWorkload, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(verrazzanocoherenceworkloadsResource, "status", c.ns, verrazzanoCoherenceWorkload), &v1alpha1.VerrazzanoCoherenceWorkload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VerrazzanoCoherenceWorkload), err
}

// Delete takes name of the verrazzanoCoherenceWorkload and deletes it. Returns an error if one occurs.
func (c *FakeVerrazzanoCoherenceWorkloads) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(verrazzanocoherenceworkloadsResource, c.ns, name, opts), &v1alpha1.VerrazzanoCoherenceWorkload{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVerrazzanoCoherenceWorkloads) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(verrazzanocoherenceworkloadsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VerrazzanoCoherenceWorkloadList{})
	return err
}

// Patch applies the patch and returns the patched verrazzanoCoherenceWorkload.
func (c *FakeVerrazzanoCoherenceWorkloads) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VerrazzanoCoherenceWorkload, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(verrazzanocoherenceworkloadsResource, c.ns, name, pt, data, subresources...), &v1alpha1.VerrazzanoCoherenceWorkload{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VerrazzanoCoherenceWorkload), err
}
