// Copyright (c) 2021, 2022, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/verrazzano/verrazzano/application-operator/apis/oam/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIngressTraits implements IngressTraitInterface
type FakeIngressTraits struct {
	Fake *FakeOamV1alpha1
	ns   string
}

var ingresstraitsResource = schema.GroupVersionResource{Group: "oam.verrazzano.io", Version: "v1alpha1", Resource: "ingresstraits"}

var ingresstraitsKind = schema.GroupVersionKind{Group: "oam.verrazzano.io", Version: "v1alpha1", Kind: "IngressTrait"}

// Get takes name of the ingressTrait, and returns the corresponding ingressTrait object, and an error if there is any.
func (c *FakeIngressTraits) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IngressTrait, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ingresstraitsResource, c.ns, name), &v1alpha1.IngressTrait{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IngressTrait), err
}

// List takes label and field selectors, and returns the list of IngressTraits that match those selectors.
func (c *FakeIngressTraits) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IngressTraitList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ingresstraitsResource, ingresstraitsKind, c.ns, opts), &v1alpha1.IngressTraitList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IngressTraitList{ListMeta: obj.(*v1alpha1.IngressTraitList).ListMeta}
	for _, item := range obj.(*v1alpha1.IngressTraitList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ingressTraits.
func (c *FakeIngressTraits) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ingresstraitsResource, c.ns, opts))

}

// Create takes the representation of a ingressTrait and creates it.  Returns the server's representation of the ingressTrait, and an error, if there is any.
func (c *FakeIngressTraits) Create(ctx context.Context, ingressTrait *v1alpha1.IngressTrait, opts v1.CreateOptions) (result *v1alpha1.IngressTrait, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ingresstraitsResource, c.ns, ingressTrait), &v1alpha1.IngressTrait{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IngressTrait), err
}

// Update takes the representation of a ingressTrait and updates it. Returns the server's representation of the ingressTrait, and an error, if there is any.
func (c *FakeIngressTraits) Update(ctx context.Context, ingressTrait *v1alpha1.IngressTrait, opts v1.UpdateOptions) (result *v1alpha1.IngressTrait, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ingresstraitsResource, c.ns, ingressTrait), &v1alpha1.IngressTrait{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IngressTrait), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIngressTraits) UpdateStatus(ctx context.Context, ingressTrait *v1alpha1.IngressTrait, opts v1.UpdateOptions) (*v1alpha1.IngressTrait, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ingresstraitsResource, "status", c.ns, ingressTrait), &v1alpha1.IngressTrait{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IngressTrait), err
}

// Delete takes name of the ingressTrait and deletes it. Returns an error if one occurs.
func (c *FakeIngressTraits) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ingresstraitsResource, c.ns, name, opts), &v1alpha1.IngressTrait{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIngressTraits) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ingresstraitsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IngressTraitList{})
	return err
}

// Patch applies the patch and returns the patched ingressTrait.
func (c *FakeIngressTraits) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IngressTrait, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ingresstraitsResource, c.ns, name, pt, data, subresources...), &v1alpha1.IngressTrait{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IngressTrait), err
}
