OCIR_REGISTRY=phx.ocir.io
OCIR_TENANCY=stevengreenberginc
CONTAINER_REGISTRY=container-registry.oracle.com

VZ_IMAGE_BASE=$OCIR_REGISTRY/$OCIR_TENANCY
VZ_IMAGE_REPO=$VZ_IMAGE_BASE/verrazzano
CERT_MANAGER_REPO=$OCIR_REGISTRY/odx-sre

OLCNE_IMAGE_REPO=$CONTAINER_REGISTRY/olcne

CERT_MANAGER_IMAGE=$CERT_MANAGER_REPO/sauron/cert-manager-controller
CERT_MANAGER_TAG=0.13.1_3
CERT_MANAGER_VERSION=0.13.1
CERT_MANAGER_SOLVER_IMAGE=$CERT_MANAGER_REPO/sauron/cert-manager-acmesolver

EXTERNAL_DNS_REPO=$OCIR_TENANCY/external-dns/external-dns
EXTERNAL_DNS_VERSION=2.20.0

GRAFANA_REPO=$OLCNE_IMAGE_REPO/grafana
GRAFANA_TAG=v6.4.4

ISTIO_CORE_DNS_PLUGIN_IMAGE=$VZ_IMAGE_REPO/istio-coredns-plugin
ISTIO_CORE_DNS_PLUGIN_TAG=0.2-istio-1.1
ISTIO_VERSION=1.4.6
ISTIO_CORE_DNS_IMAGE=$OLCNE_IMAGE_REPO/coredns
ISTIO_CORE_DNS_TAG=1.6.2

KEYCLOAK_IMAGE_TAG=10.0.1_3
KEYCLOAK_CHART_VERSION=8.2.2

NGINX_INGRESS_CONTROLLER_IMAGE=$VZ_IMAGE_BASE/ingress-nginx/ingress-nginx
NGINX_INGRESS_CONTROLLER_TAG=0.32-0
NGINX_INGRESS_CONTROLLER_VERSION=1.27.0
NGINX_DEFAULT_BACKEND_IMAGE=$VZ_IMAGE_BASE/ingress-nginx/custom-error-pages
NGINX_DEFAULT_BACKEND_TAG=0.32-0

RANCHER_IMAGE=phx.ocir.io/stevengreenberginc/rancher/rancher
RANCHER_VERSION=v2.4.3