// Copyright (c) 2021, 2022, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "github.com/verrazzano/verrazzano/application-operator/clientset/versioned"
	appv1alpha1 "github.com/verrazzano/verrazzano/application-operator/clientset/versioned/typed/app/v1alpha1"
	fakeappv1alpha1 "github.com/verrazzano/verrazzano/application-operator/clientset/versioned/typed/app/v1alpha1/fake"
	clustersv1alpha1 "github.com/verrazzano/verrazzano/application-operator/clientset/versioned/typed/clusters/v1alpha1"
	fakeclustersv1alpha1 "github.com/verrazzano/verrazzano/application-operator/clientset/versioned/typed/clusters/v1alpha1/fake"
	oamv1alpha1 "github.com/verrazzano/verrazzano/application-operator/clientset/versioned/typed/oam/v1alpha1"
	fakeoamv1alpha1 "github.com/verrazzano/verrazzano/application-operator/clientset/versioned/typed/oam/v1alpha1/fake"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	o := testing.NewObjectTracker(scheme, codecs.UniversalDecoder())
	for _, obj := range objects {
		if err := o.Add(obj); err != nil {
			panic(err)
		}
	}

	cs := &Clientset{tracker: o}
	cs.discovery = &fakediscovery.FakeDiscovery{Fake: &cs.Fake}
	cs.AddReactor("*", "*", testing.ObjectReaction(o))
	cs.AddWatchReactor("*", func(action testing.Action) (handled bool, ret watch.Interface, err error) {
		gvr := action.GetResource()
		ns := action.GetNamespace()
		watch, err := o.Watch(gvr, ns)
		if err != nil {
			return false, nil, err
		}
		return true, watch, nil
	})

	return cs
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.discovery
}

func (c *Clientset) Tracker() testing.ObjectTracker {
	return c.tracker
}

var (
	_ clientset.Interface = &Clientset{}
	_ testing.FakeClient  = &Clientset{}
)

// AppV1alpha1 retrieves the AppV1alpha1Client
func (c *Clientset) AppV1alpha1() appv1alpha1.AppV1alpha1Interface {
	return &fakeappv1alpha1.FakeAppV1alpha1{Fake: &c.Fake}
}

// ClustersV1alpha1 retrieves the ClustersV1alpha1Client
func (c *Clientset) ClustersV1alpha1() clustersv1alpha1.ClustersV1alpha1Interface {
	return &fakeclustersv1alpha1.FakeClustersV1alpha1{Fake: &c.Fake}
}

// OamV1alpha1 retrieves the OamV1alpha1Client
func (c *Clientset) OamV1alpha1() oamv1alpha1.OamV1alpha1Interface {
	return &fakeoamv1alpha1.FakeOamV1alpha1{Fake: &c.Fake}
}
