// Copyright (c) 2021, 2022, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type IngressTraitExpansion interface{}

type LoggingTraitExpansion interface{}

type MetricsTraitExpansion interface{}

type VerrazzanoCoherenceWorkloadExpansion interface{}

type VerrazzanoHelidonWorkloadExpansion interface{}

type VerrazzanoWebLogicWorkloadExpansion interface{}
