// Copyright (c) 2021, 2022, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/verrazzano/verrazzano/application-operator/apis/oam/v1alpha1"
	scheme "github.com/verrazzano/verrazzano/application-operator/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VerrazzanoGenericWorkloadsGetter has a method to return a VerrazzanoGenericWorkloadInterface.
// A group's client should implement this interface.
type VerrazzanoGenericWorkloadsGetter interface {
	VerrazzanoGenericWorkloads(namespace string) VerrazzanoGenericWorkloadInterface
}

// VerrazzanoGenericWorkloadInterface has methods to work with VerrazzanoGenericWorkload resources.
type VerrazzanoGenericWorkloadInterface interface {
	Create(ctx context.Context, verrazzanoGenericWorkload *v1alpha1.VerrazzanoGenericWorkload, opts v1.CreateOptions) (*v1alpha1.VerrazzanoGenericWorkload, error)
	Update(ctx context.Context, verrazzanoGenericWorkload *v1alpha1.VerrazzanoGenericWorkload, opts v1.UpdateOptions) (*v1alpha1.VerrazzanoGenericWorkload, error)
	UpdateStatus(ctx context.Context, verrazzanoGenericWorkload *v1alpha1.VerrazzanoGenericWorkload, opts v1.UpdateOptions) (*v1alpha1.VerrazzanoGenericWorkload, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VerrazzanoGenericWorkload, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VerrazzanoGenericWorkloadList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VerrazzanoGenericWorkload, err error)
	VerrazzanoGenericWorkloadExpansion
}

// verrazzanoGenericWorkloads implements VerrazzanoGenericWorkloadInterface
type verrazzanoGenericWorkloads struct {
	client rest.Interface
	ns     string
}

// newVerrazzanoGenericWorkloads returns a VerrazzanoGenericWorkloads
func newVerrazzanoGenericWorkloads(c *OamV1alpha1Client, namespace string) *verrazzanoGenericWorkloads {
	return &verrazzanoGenericWorkloads{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the verrazzanoGenericWorkload, and returns the corresponding verrazzanoGenericWorkload object, and an error if there is any.
func (c *verrazzanoGenericWorkloads) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VerrazzanoGenericWorkload, err error) {
	result = &v1alpha1.VerrazzanoGenericWorkload{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("verrazzanogenericworkloads").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VerrazzanoGenericWorkloads that match those selectors.
func (c *verrazzanoGenericWorkloads) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VerrazzanoGenericWorkloadList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VerrazzanoGenericWorkloadList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("verrazzanogenericworkloads").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested verrazzanoGenericWorkloads.
func (c *verrazzanoGenericWorkloads) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("verrazzanogenericworkloads").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a verrazzanoGenericWorkload and creates it.  Returns the server's representation of the verrazzanoGenericWorkload, and an error, if there is any.
func (c *verrazzanoGenericWorkloads) Create(ctx context.Context, verrazzanoGenericWorkload *v1alpha1.VerrazzanoGenericWorkload, opts v1.CreateOptions) (result *v1alpha1.VerrazzanoGenericWorkload, err error) {
	result = &v1alpha1.VerrazzanoGenericWorkload{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("verrazzanogenericworkloads").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(verrazzanoGenericWorkload).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a verrazzanoGenericWorkload and updates it. Returns the server's representation of the verrazzanoGenericWorkload, and an error, if there is any.
func (c *verrazzanoGenericWorkloads) Update(ctx context.Context, verrazzanoGenericWorkload *v1alpha1.VerrazzanoGenericWorkload, opts v1.UpdateOptions) (result *v1alpha1.VerrazzanoGenericWorkload, err error) {
	result = &v1alpha1.VerrazzanoGenericWorkload{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("verrazzanogenericworkloads").
		Name(verrazzanoGenericWorkload.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(verrazzanoGenericWorkload).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *verrazzanoGenericWorkloads) UpdateStatus(ctx context.Context, verrazzanoGenericWorkload *v1alpha1.VerrazzanoGenericWorkload, opts v1.UpdateOptions) (result *v1alpha1.VerrazzanoGenericWorkload, err error) {
	result = &v1alpha1.VerrazzanoGenericWorkload{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("verrazzanogenericworkloads").
		Name(verrazzanoGenericWorkload.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(verrazzanoGenericWorkload).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the verrazzanoGenericWorkload and deletes it. Returns an error if one occurs.
func (c *verrazzanoGenericWorkloads) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("verrazzanogenericworkloads").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *verrazzanoGenericWorkloads) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("verrazzanogenericworkloads").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched verrazzanoGenericWorkload.
func (c *verrazzanoGenericWorkloads) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VerrazzanoGenericWorkload, err error) {
	result = &v1alpha1.VerrazzanoGenericWorkload{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("verrazzanogenericworkloads").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
