#!/bin/bash

# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

SCRIPT_DIR=$(cd $(dirname "$0"); pwd -P)

GO_REPO_PATH=$1
TEST_CONFIG_FILE=$2
DOCKER_REPO=$3
KUBECONFIG=$4
OCR_USERNAME=$5
OCR_PASSWORD=$6
ENV_NAME=$7


cd ${SCRIPT_DIR}/
cp testConfigTemplate.yaml ${TEST_CONFIG_FILE}
sed -i "s#XX_MGMT_KUBECONFIG_XX#${KUBECONFIG}#" ${TEST_CONFIG_FILE}
sed -i "s/XX_ENV_NAME_XX/${ENV_NAME}/" ${TEST_CONFIG_FILE}
sed -i "s/XX_OCIR_REPO_XX/${DOCKER_REPO}/" ${TEST_CONFIG_FILE}
sed -i "s/XX_OCR_USERNAME_XX/${OCR_USERNAME}/" ${TEST_CONFIG_FILE}
sed -i "s/XX_OCR_PASSWORD_XX/${OCR_PASSWORD}/" ${TEST_CONFIG_FILE}
sed -i "s#XX_SOCKS_MODEL_FILE_XX#${SOCKS_MODEL_FILE}#" ${TEST_CONFIG_FILE}
sed -i "s#XX_SOCKS_BINDING_FILE_XX#${SOCKS_BINDING_FILE}#" ${TEST_CONFIG_FILE}
sed -i "s#XX_BOBS_MODEL_FILE_XX#${BOBS_MODEL_FILE}#" ${TEST_CONFIG_FILE}
sed -i "s#XX_BOBS_BINDING_FILE_XX#${BOBS_BINDING_FILE}#" ${TEST_CONFIG_FILE}
sed -i "s#XX_BOBS_MYSQL_DEPLOY_FILE_XX#${BOBS_MYSQL_DEPLOY_FILE}#" ${TEST_CONFIG_FILE}
sed -i "s#XX_HELIDON_MODEL_FILE_XX#${HELIDON_UPGRADE_MODEL_FILE}#" ${TEST_CONFIG_FILE}
sed -i "s#XX_HELIDON_BINDING_FILE_XX#${HELIDON_UPGRADE_BINDING_FILE}#" ${TEST_CONFIG_FILE}
