// Copyright (c) 2020, 2021, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/verrazzano/verrazzano/platform-operator/apis/verrazzano/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVerrazzanoComponents implements VerrazzanoComponentInterface
type FakeVerrazzanoComponents struct {
	Fake *FakeVerrazzanoV1alpha1
	ns   string
}

var verrazzanocomponentsResource = schema.GroupVersionResource{Group: "install.verrazzano.io", Version: "v1alpha1", Resource: "verrazzanocomponents"}

var verrazzanocomponentsKind = schema.GroupVersionKind{Group: "install.verrazzano.io", Version: "v1alpha1", Kind: "VerrazzanoComponent"}

// Get takes name of the verrazzanoComponent, and returns the corresponding verrazzanoComponent object, and an error if there is any.
func (c *FakeVerrazzanoComponents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VerrazzanoComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(verrazzanocomponentsResource, c.ns, name), &v1alpha1.VerrazzanoComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VerrazzanoComponent), err
}

// List takes label and field selectors, and returns the list of VerrazzanoComponents that match those selectors.
func (c *FakeVerrazzanoComponents) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VerrazzanoComponentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(verrazzanocomponentsResource, verrazzanocomponentsKind, c.ns, opts), &v1alpha1.VerrazzanoComponentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VerrazzanoComponentList{ListMeta: obj.(*v1alpha1.VerrazzanoComponentList).ListMeta}
	for _, item := range obj.(*v1alpha1.VerrazzanoComponentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested verrazzanoComponents.
func (c *FakeVerrazzanoComponents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(verrazzanocomponentsResource, c.ns, opts))

}

// Create takes the representation of a verrazzanoComponent and creates it.  Returns the server's representation of the verrazzanoComponent, and an error, if there is any.
func (c *FakeVerrazzanoComponents) Create(ctx context.Context, verrazzanoComponent *v1alpha1.VerrazzanoComponent, opts v1.CreateOptions) (result *v1alpha1.VerrazzanoComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(verrazzanocomponentsResource, c.ns, verrazzanoComponent), &v1alpha1.VerrazzanoComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VerrazzanoComponent), err
}

// Update takes the representation of a verrazzanoComponent and updates it. Returns the server's representation of the verrazzanoComponent, and an error, if there is any.
func (c *FakeVerrazzanoComponents) Update(ctx context.Context, verrazzanoComponent *v1alpha1.VerrazzanoComponent, opts v1.UpdateOptions) (result *v1alpha1.VerrazzanoComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(verrazzanocomponentsResource, c.ns, verrazzanoComponent), &v1alpha1.VerrazzanoComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VerrazzanoComponent), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVerrazzanoComponents) UpdateStatus(ctx context.Context, verrazzanoComponent *v1alpha1.VerrazzanoComponent, opts v1.UpdateOptions) (*v1alpha1.VerrazzanoComponent, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(verrazzanocomponentsResource, "status", c.ns, verrazzanoComponent), &v1alpha1.VerrazzanoComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VerrazzanoComponent), err
}

// Delete takes name of the verrazzanoComponent and deletes it. Returns an error if one occurs.
func (c *FakeVerrazzanoComponents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(verrazzanocomponentsResource, c.ns, name), &v1alpha1.VerrazzanoComponent{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVerrazzanoComponents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(verrazzanocomponentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VerrazzanoComponentList{})
	return err
}

// Patch applies the patch and returns the patched verrazzanoComponent.
func (c *FakeVerrazzanoComponents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VerrazzanoComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(verrazzanocomponentsResource, c.ns, name, pt, data, subresources...), &v1alpha1.VerrazzanoComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VerrazzanoComponent), err
}
